name: Configured Actions
on:
  push:
  
jobs:
  Preconfigured-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
            CCN: 3
